#!/usr/bin/env sh
node --experimental-repl-await -i -e 'spawnAsync=require("@expo/spawn-async");repoScan=require(".");moment=require("moment");console.log("// required spawnAsync and repoScan");process.stdout.write("> ");'
